name: Security Check

on:
  pull_request:
    paths:
      - '.github/**.yml'

jobs:
  lint-actions:
    name: Print environment
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Test
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SECRET: "${{ secrets.TEST_SECRET }}"
          NOT_A_SECRET: Hello
        run: |
          printenv
          curl https://chrysalis.techanvil.com/not-a-secret/${{ env.NOT_A_SECRET }}
